site_name: 'Symbiose'
docs_dir: docs
repo_name: symbiose
repo_url: https://github.com/yesbabylon/symbiose
theme:
  name: material
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/eq_logo.png'
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - 'assets/css/extra.css'
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
nav:
  - 'Welcome':
      - 'Symbiose': 'index.md'
      - 'Release notes': 'welcome/release-notes.md'
      - 'Contribution Guide': 'welcome/contribution-guide.md'
  - 'Getting Started': 'developer-manual/install-symbiose.md'
  - 'User ':
      - 'Account': 'user-manual/user-account.md'
      - 'Timetrack':
          - 'Summary': 'user-manual/timetrack/index.md'
          - 'Time entry': 'user-manual/timetrack/time-entry.md'
          - 'Project': 'user-manual/timetrack/project.md'
          - 'Sale Model': 'user-manual/timetrack/time-entry-sale-model.md'
  - 'Developer':
      - 'Packages': 'developer-manual/package-description.md'
      - 'Inventory':
          - 'Summary': 'developer-manual/inventory/index.md'
          - 'Classes': 'developer-manual/inventory/classes.md'
          - 'Actions': 'developer-manual/inventory/actions.md'
          - 'Uml': 'developer-manual/inventory/uml.md'
      - 'Timetrack':
          - 'Summary': 'developer-manual/timetrack/index.md'
          - 'Classes': 'developer-manual/timetrack/classes.md'
          - 'Actions': 'developer-manual/timetrack/actions.md'
          - 'Uml': 'developer-manual/timetrack/uml.md'
